import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavbarSection from "../components/navbar";
import FooterSection from "@/components/footer";
import ReduxProvider from "@/store/ReduxProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ReduxProvider>
      <html lang="en">
        <body className={`bg-white dark:bg-black ${inter.className}`}>
          <NavbarSection />
          {children}
          <FooterSection />
        </body>
      </html>
    </ReduxProvider>
  );
}
